server:
  port: 8080
  #swagger url:http://localhost:8090/swagger-ui.html (端口和server.port相同)

spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
    url: jdbc:h2:mem:chess
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    initialization-mode: always

  jpa:
    database: h2
    hibernate:
      ddl-auto: update

  #H2控制台:http://localhost:8090/h2-console
  h2:
    console:
      path: /h2-console
      enabled: true

git:
  url: https://github.com/st-aop.git
  username:
  password:
  local:
    clone-path: D://gitProject/st-aop
    repository-path: D://gitProject/st-aop/.git